places = ['peru', 'chile', 'patagonia', 'irlanda', 'canada']
print(places)
print(sorted(places))
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
places.sort()
print(places)
places.sort(reverse=True)
print(places)